### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by altcnews** [cal97g/livermore#1]
Hi,
I've got this error during the docker installation:

bot_1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "xd" to address: Name or service not known
bot_1  |  (Background on this error at: http://sqlalche.me/e/e3q8)
docker_bot_1 exited with code 1

Could you please help?
Thank You.

**Comment by cal97g** [comment]
Hi, looks like you're running the production docker-compose, make sure you're using development. If using production you will have to host a postgresql server somewhere and update the config with a real address.

**Comment by altcnews** [comment]
Hi, thank you for your info
I'll find out then.
